token:
  secret:
    key: SpringBootJwtHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234