spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: MySQL
        hbm2ddl:
          auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/Delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234