version: '3.7'
services:
  rabbitmq-delivery:
    container_name: rabbitmqDelivery
    image: rabbitmq:management
    ports:
      - "5672:5672" # rabbit amqp port
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234